---
development:
  cloud_name: hbubqhmen
  api_key: '668345633214392'
  api_secret: 3gVcqfVcD9j2PQxrNw35-Awv_Co
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hbubqhmen
  api_key: '668345633214392'
  api_secret: 3gVcqfVcD9j2PQxrNw35-Awv_Co
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hbubqhmen
  api_key: '668345633214392'
  api_secret: 3gVcqfVcD9j2PQxrNw35-Awv_Co
  enhance_image_tag: true
  static_image_support: false
